import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const source = "/Users/adam/Documents/ICT新闻简报-伊拉克/outputs/government-monitoring-matrix-20260906/伊拉克-约旦-黎巴嫩政府人员监控矩阵_v1.0.xlsx";
const target = "/Users/adam/Documents/ICT新闻简报-伊拉克/levant-pages-repo/personnel-monitoring.html";
const wb = await SpreadsheetFile.importXlsx(await FileBlob.load(source));
const countries = ["伊拉克", "约旦", "黎巴嫩"];
const data = [];
for (const country of countries) {
  const sheet = wb.worksheets.getItem(country);
  const values = sheet.getRange(`A4:M${country === "约旦" ? 33 : 27}`).values;
  for (const row of values) {
    if (!row[0]) continue;
    data.push({id:row[0],country:row[1],name:row[2],role:row[3],tg:row[4],fb:row[5],x:row[6],li:row[7],account:row[8],person:row[9],verified:"2026-09-06",source:row[11],priority:row[12]});
  }
}
const safeJson = JSON.stringify(data).replaceAll("<", "\\u003c");
const html = `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>政府人员监控矩阵 · 黎凡特 ICT 双周简报</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#EDEAE4;color:#172033;font-family:-apple-system,'Segoe UI','PingFang SC',Arial,sans-serif}.page{max-width:1240px;margin:22px auto;background:white;border-radius:14px;overflow:hidden;border:1px solid #d9d6cf;box-shadow:0 8px 28px rgba(23,32,51,.08)}header{background:#042C53;color:white;padding:22px 26px}.back{color:#B5D4F4;text-decoration:none;font-size:12px}.back:hover{text-decoration:underline}h1{font-size:22px;margin:10px 0 5px}.meta{font-size:12px;color:rgba(255,255,255,.65)}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:16px;background:#F5F3EF}.stat{background:white;border:1px solid #e5e2dc;border-radius:9px;padding:12px}.n{font-size:23px;font-weight:700}.l{font-size:11px;color:#777;margin-top:3px}.tools{padding:14px 16px;display:flex;gap:8px;flex-wrap:wrap;border-bottom:1px solid #e5e2dc}.tools input{flex:1;min-width:220px;padding:9px 12px;border:1px solid #cbc7bf;border-radius:8px}.filter{border:1px solid #cbc7bf;background:#fff;padding:8px 12px;border-radius:8px;cursor:pointer}.filter.active{background:#042C53;color:white;border-color:#042C53}.download{margin-left:auto;background:#E8C76F;color:#3D2F05;text-decoration:none;padding:8px 13px;border-radius:8px;font-size:12px;font-weight:700}.note{margin:14px 16px;padding:11px 13px;background:#FFF8E8;border-left:4px solid #E8C76F;font-size:12px;line-height:1.6}.table-wrap{overflow:auto;padding:0 16px 20px;max-height:70vh}table{width:100%;border-collapse:collapse;font-size:12px;min-width:1120px}th{position:sticky;top:0;background:#263449;color:white;text-align:left;padding:9px 7px;z-index:2}td{padding:8px 7px;border-bottom:1px solid #ece9e4;vertical-align:top}tr:hover{background:#FAF8F0}.iq{border-left:4px solid #C13515}.jo{border-left:4px solid #0656A0}.lb{border-left:4px solid #2F7A2F}.pill{display:inline-block;padding:2px 7px;border-radius:10px;font-size:10px;white-space:nowrap}.ok{background:#DDF3E4;color:#176B35}.wait{background:#FFF1C7;color:#805400}.social{display:flex;gap:5px;flex-wrap:wrap}.social a{color:#0656A0;text-decoration:none;background:#E6F1FB;padding:2px 6px;border-radius:6px}.source{color:#65758B;text-decoration:none}.empty{text-align:center;padding:30px;color:#777}footer{text-align:center;padding:15px;color:#888;font-size:11px;border-top:1px solid #ece9e4}@media(max-width:700px){.page{margin:0;border-radius:0}.stats{grid-template-columns:repeat(2,1fr)}header{padding:18px}.download{margin-left:0}}
</style></head><body><main class="page"><header><a class="back" href="./">← 返回 ICT 双周简报</a><h1>政府人员监控矩阵</h1><div class="meta">伊拉克 · 约旦 · 黎巴嫩｜国家级元首、总理及现任内阁｜V1.0 · 2026-09-06</div></header>
<section class="stats"><div class="stat"><div class="n" id="total">78</div><div class="l">纳入岗位</div></div><div class="stat"><div class="n">24</div><div class="l">🇮🇶 伊拉克</div></div><div class="stat"><div class="n">30</div><div class="l">🇯🇴 约旦</div></div><div class="stat"><div class="n">24</div><div class="l">🇱🇧 黎巴嫩</div></div></section>
<section class="tools"><input id="search" placeholder="搜索姓名、职务或国家……"><button class="filter active" data-country="全部">全部</button><button class="filter" data-country="伊拉克">伊拉克</button><button class="filter" data-country="约旦">约旦</button><button class="filter" data-country="黎巴嫩">黎巴嫩</button><a class="download" href="政府人员监控矩阵_v1.0.xlsx" download>下载 Excel</a></section>
<div class="note">姓名和社媒只在一手来源可确认时录入；“待核验”不是人员缺位，而是尚未完成官方交叉核验。当前伊拉克已接入外交部、国防部、内政部、通信部、通信监管机构及高教部六个 Telegram 新闻源。</div>
<div class="table-wrap"><table><thead><tr><th>国家</th><th>姓名</th><th>现任职务</th><th>官方社媒</th><th>账号状态</th><th>人员状态</th><th>最后核验</th><th>来源</th><th>优先级</th></tr></thead><tbody id="rows"></tbody></table><div id="empty" class="empty" hidden>没有符合条件的人员</div></div>
<footer>伊拉克代表处 ICT 双周简报 · 人员监控模块</footer></main>
<script>const people=${safeJson};let country='全部';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const link=(u,t)=>u?'<a href="'+esc(u)+'" target="_blank" rel="noopener">'+t+'</a>':'';function render(){const q=document.querySelector('#search').value.toLowerCase();const list=people.filter(p=>(country==='全部'||p.country===country)&&Object.values(p).join(' ').toLowerCase().includes(q));document.querySelector('#total').textContent=list.length;document.querySelector('#rows').innerHTML=list.map(p=>{const cls=p.country==='伊拉克'?'iq':p.country==='约旦'?'jo':'lb';const socials=[link(p.tg,'TG'),link(p.fb,'FB'),link(p.x,'X'),link(p.li,'IN')].filter(Boolean).join('');const ok=p.account.includes('已核验');return '<tr class="'+cls+'"><td>'+esc(p.country)+'</td><td><b>'+esc(p.name)+'</b></td><td>'+esc(p.role)+'</td><td><div class="social">'+(socials||'—')+'</div></td><td><span class="pill '+(ok?'ok':'wait')+'">'+esc(p.account)+'</span></td><td>'+esc(p.person)+'</td><td>'+esc(p.verified)+'</td><td><a class="source" href="'+esc(p.source)+'" target="_blank" rel="noopener">官方来源 ↗</a></td><td>'+esc(p.priority)+'</td></tr>'}).join('');document.querySelector('#empty').hidden=list.length>0}document.querySelector('#search').addEventListener('input',render);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');country=b.dataset.country;render()}));render();</script></body></html>`;
await fs.writeFile(target, html, "utf8");
console.log(`wrote ${target} with ${data.length} rows`);
